oauth:
  providers:
    kakao:
      provider: kakao
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      authorize-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      redirect-uri: ${SERVER_HOST}/oauth/kakao/callback
      fields:
        id: id
        email: kakao_account.email
        nickname: kakao_account.profile.nickname
    google:
      provider: google
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      authorize-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
      redirect-uri: ${SERVER_HOST}/oauth/google/callback
      scope: openid profile email
      fields:
        id: sub
        email: email
        nickname: name