### [학생] 댓글 작성
POST {{distributeHost}}/boards/1/comments
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "content": "학생이 작성한 댓글입니다."
}


### [학생] 댓글 수정
PUT {{distributeHost}}/boards/1/comments/2
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "content": "학생이 수정한 댓글입니다."
}

### [튜터] 대댓글 작성
POST {{distributeHost}}/boards/1/comments/3/reply
Authorization: Bearer {{tutorAccessToken}}
Content-Type: application/json

{
  "content": "튜터가 작성한 대댓글입니다."
}


### [학생] 댓글 전체 조회 (유저, 튜터)
GET {{distributeHost}}/boards/1/comments
Authorization: Bearer {{studentAccessToken}}


### [학생] 댓글 추천
POST {{distributeHost}}/comments/1/like
Authorization: Bearer {{tutorAccessToken}}


### [학생] 댓글 추천 취소
DELETE {{distributeHost}}/comments/1/like
Authorization: Bearer {{studentAccessToken}}