### 게시글 삭제
DELETE {{distributeHost}}/boards/1
Authorization: Bearer {{studentAccessToken}}

### [학생] 댓글 삭제
DELETE {{distributeHost}}/boards/1/comments/1
Authorization: Bearer {{studentAccessToken}}

### 학생 로그아웃
POST {{distributeHost}}/auth/logout
Authorization: Bearer {{studentAccessToken}}

### 다른 학생 로그아웃
POST {{distributeHost}}/auth/logout
Authorization: Bearer {{anotherStudentAccessToken}}

### 학생 회원탈퇴
DELETE {{distributeHost}}/auth/withdraw
Authorization: Bearer {{studentAccessToken}}

### 튜터 로그아웃
POST {{distributeHost}}/auth/logout
Authorization: Bearer {{tutorAccessToken}}

### 튜터 회원탈퇴
DELETE {{distributeHost}}/auth/withdraw
Authorization: Bearer {{tutorAccessToken}}

### 관리자 로그아웃
POST {{distributeHost}}/auth/logout
Authorization: Bearer {{adminAccessToken}}

### 학생 액세스 토큰 재발급
POST {{distributeHost}}auth/refresh
Authorization: Bearer {{studentAccessToken}}
Refresh: {{studentRefreshToken}}}