### GET request to example server 전체 알림 확인
GET {{distributeHost}}/notifications
Authorization: Bearer {{tutorAccessToken}}


### 미확인 알림 갯수 확인
GET {{distributeHost}}/notifications/count
Authorization: Bearer {{tutorAccessToken}}


### 알림 확인
PATCH {{distributeHost}}/notifications/2
Authorization: Bearer {{tutorAccessToken}}