### 기술 스택 종류 조회
GET {{distributeHost}}/tech-stacks
Authorization: Bearer {{studentAccessToken}}

### 기술 스택 추가 (튜터)
POST {{distributeHost}}/tech-stacks?techId=4
Authorization: Bearer {{tutorAccessToken}}

### 기술 스택 추가 (학생)
POST {{distributeHost}}/tech-stacks?techId=2
Authorization: Bearer {{studentAccessToken}}

### 기술 스택 삭제 (튜터)
DELETE {{distributeHost}}/tech-stacks/1
Authorization: Bearer {{tutorAccessToken}}

### 기술 스택 삭제 (학생)
DELETE {{distributeHost}}/tech-stacks/2
Authorization: Bearer {{studentAccessToken}}

### 내가 선택한 기술 스택 조회 (튜터, 학생)
GET {{distributeHost}}/tech-stacks/me
Authorization: Bearer {{studentAccessToken}}

