### 내 프로필 조회
GET {{distributeHost}}/users/me
Authorization: Bearer {{studentAccessToken}}

### 내 프로필 수정
PUT {{distributeHost}}/users/me
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "name": "학생1",
  "address": "주소 등록",
  "introduction": "소개글 등록"
}

### 비밀번호 수정
PATCH {{distributeHost}}/users/me
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "oldPassword" : "asdasdjkDF23",
  "newPassword" : "NEWasdasdjkDF23"
}

### 비밀번호 찾기 - 인증키 발송
POST {{distributeHost}}/users/find
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "email" : "soonch6@naver.com"
}

### 비밀번호 찾기 - 새로운 비밀번호
PATCH {{distributeHost}}/users/find
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "email" : "soonch6@naver.com",
  "authNumber" : "822524",
  "newPassword" : "Asdf1234"
}

### 튜터 목록조회
GET {{distributeHost}}/users/tutorList
Authorization: Bearer {{tutorAccessToken5}}

### 매칭
GET {{distributeHost}}/tutor
Authorization: Bearer {{studentAccessToken}}


