name: CI/CD for dev branch

on:
  push:
    branches:
      - dev

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build bootJar
        run: ./gradlew bootJar
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FEEDPREP_ACCESS_KEY: ${{ secrets.FEEDPREP_ACCESS_KEY }}
          FEEDPREP_SECRET_KEY: ${{ secrets.FEEDPREP_SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_AUTH: ${{ secrets.TEST_AUTH }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PORTONE_STOREID: ${{ secrets.PORTONE_STOREID }}
          PORTONE_APISECRET: ${{ secrets.PORTONE_APISECRET }}
          PORTONE_WEBHOOK_SECRET: ${{ secrets.PORTONE_WEBHOOK_SECRET }}
          PORTONE_CHANNELKEY: ${{ secrets.PORTONE_CHANNELKEY }}
          EC2_URL: ${{ secrets.EC2_URL }}

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/feedprep:1.0 .

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/feedprep:1.0